### ISSUE TITLE
JanusGraph version is outdated

### ISSUE THREAD

**Issue by rngcntr** [JanusGraph/janusgraph-foundationdb#11]
The code is still running on JanusGraph version 0.3.0 which should be updated to the most recent version.

**Comment by blindenvy** [comment]
What will our intention be in supporting various JG versions? Will we only support the latest JG version? Or do we expect to maintain a version of this adapter for each JG version that is still receiving updates? IE. Have a fdb adapter for JG 3.x, 4.x, 5.x if those are the JG versions still currently being developed.

**Comment by porunov** [comment]
Version 0.5.x and 0.6.x (not released yet) are the only supported versions currently. Version 0.4.x and below are EOL.

**Comment by farodin91** [comment]
Fixed  by #26
