### ISSUE TITLE
Update package and directory names

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph-foundationdb#20]
We need to do something similar to https://github.com/JanusGraph/janusgraph/pull/2/commits/0b6053375a94c7ab28f9ec4552e416783e4147d7 here, specifically:

* [move files](https://github.com/JanusGraph/janusgraph/pull/2/commits/0b6053375a94c7ab28f9ec4552e416783e4147d7) from `com/experoinc/janusgraph` &rarr; `org/janusgraph`
* [update package names](https://github.com/JanusGraph/janusgraph/pull/2/commits/fdf6ce99ecf7b1e417375f1d35826fc1768aa3da) from `com.experoinc.janusgraph` &rarr; `org.janusgraph`

The links above point to the original cleanup commits in JanusGraph (coming from Titan), and may be useful for this cleanup.

However, before making these large-scale changes, it would be very handy to have a working [`.travis.yml` config](https://github.com/JanusGraph/janusgraph-foundationdb/issues/19), so that these changes automatically tested.

**Comment by FlorianHockmann** [comment]
I think this is a duplicate of #10 for which we already have an open PR: #17. Although waiting for a Travis build probably still makes sense.

**Comment by mbrukman** [comment]
@FlorianHockmann — you're right, good catch!
